name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  run-build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y rpm

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.13

      - name: Run go vet
        run: make vet

      - name: Build binaries
        run: make build

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: mieru
          path: |
            release/*.deb
            release/*.rpm
            release/*.tar.gz
            release/*.zip
          if-no-files-found: error

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: AES
          files: |
            release/*.deb
            release/*.rpm
            release/*.tar.gz
            release/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload code coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: |
            coverage.html
